### ISSUE TITLE
Don't have a yt_md_link / lesson before creating youtube videos for the first time

### ISSUE THREAD

**Issue by LucyMcGowan** [muschellij2/didactr#8]
First of all, this 📦 is awesome, thank you both for all of your work on it!

I get a lot of warnings when I run the various functions, mostly around `object 'yt_md_link ' not found`, but if I haven't created YouTube videos yet, I don't have links to include. This is kind of a pain, but not such a big deal since it is just a warning.

I believe related to this, when I try to make the youtube links for the first time, I get the error `object 'lesson' not found`.  I believe it is related to these lines (but admittedly don't fully understand what's going on here -- even if the user inputs something as `lesson` are you changing it to `NULL` and then removing it?). In the second code chunk, it seems that you need to have an object `lesson` to check if it is `NULL` (at least this is where I error when trying to debug the function itself). 

https://github.com/muschellij2/didactr/blob/2400288543e89de8b6dcfb9f0eaa8cf28bd346a5/R/update_youtube.R#L21-L22

https://github.com/muschellij2/didactr/blob/2400288543e89de8b6dcfb9f0eaa8cf28bd346a5/R/update_youtube.R#L53-L60

Is there an obvious way to get around this so I can run without errors?

**Comment by muschellij2** [comment]
The first set are for lines are to remove NOTEs in the R CMD check as `dplyr` uses NSE, but there is a bug in that code as I'm removing `lesson` even if passed into the function.    See 

I could use 
```r
## quiets concerns of R CMD check re: the .'s that appear in pipelines
if(getRversion() >= "2.15.1")  utils::globalVariables(c("."))
``` 
(with other variables in each function)

as mentioned in https://github.com/STAT545-UBC/Discussion/issues/451 but I had seen `"globalVariables is a hideous hack and I will never use it. "` in the post
https://stackoverflow.com/questions/9439256/how-can-i-handle-r-cmd-check-no-visible-binding-for-global-variable-notes-when, but it seems as though hadley had changed his mind.
