### ISSUE TITLE
No value for up$url, causing an error in update_youtube (and therefore vids_to_youtube)

### ISSUE THREAD

**Issue by LucyMcGowan** [muschellij2/didactr#9]
My `up` (generated from `tuber::upload_video()` inside the `vids_to_youtube()` function) does not have a named list component called `url`, so running `vids_to_youtube()`, which in turn calls `update_youtube()` fails with error:

```
Error in mutate_impl(.data, dots) : 
  Column `url` is of unsupported type NULL
```

At the top level, `up` only contains the following:
* `request`
* `content`
* `file`
* `lesson`
* `metric_path`

https://github.com/muschellij2/didactr/blob/374329156bf39798872327a31793619c1b5c2fd2/R/update_youtube.R#L64-L71

**Comment by muschellij2** [comment]
This is due to an insufficient version req on `tuber`.  I have updated `didactr` to require this.  
Please reinstall `didactr` and if you get an error with `tuber` version, please install using 
```r
devtools::install_github("soodoku/tuber")
```
